print("Hello World!")
print("Yaay I am having fun here!")
print("This is great!")
print("Memelords have arrived!")
print("Notice the circle at the top")
print("Hello World!")
print("Yaay I am having fun here!")
print("This is great!")
print("Memelords have arrived!")
print("Notice the circle at the top")
